### ISSUE TITLE
Command parse failed

### ISSUE THREAD

**Issue by dimovic69** [gitbls/internet-monitor#2]
Got 'Command parse failed' when  using option --pingwait N 

As far as I see --pingwait is not included in line 271 of the script

OARGS=$(getopt -o h --longoptions help,action:,datefmt:,ddns,einterval:,internet:,interval:,noping,ping:,pingcount:,standby:,syslog -n $script -- "$@")

I added it manually and reported this issue.

**Comment by gitbls** [comment]
Ugh and 😲 How did I manage to do that? Thanks for pointing it out. Fixed.
