### ISSUE TITLE
Failed to enable unit

### ISSUE THREAD

**Issue by namork** [gitbls/internet-monitor#4]
i get this message after installing: 

udo systemctl enable [--now] internet-monitor
Invalid unit name "[--now]" was escaped as "\x5b--now\x5d" (maybe you should use systemd-escape?)
Failed to enable unit: Unit file \x5b--now\x5d.service does not exist.

**Comment by gitbls** [comment]
When used in the middle of the documentation for a command line, the construct `[--switch]` means that the switch is optional. 

For instance, you can type `sudo systemctl enable internet-monitor` which will set the service to start on the next system reboot, but do nothing in the running system.

Or, you can type `sudo systemctl enable --now internet-monitor` which sets the service to start on the next system reboot AND starts the service running in the current system.

**Comment by gitbls** [comment]
Closing since no further input from @namork. Please re-open this issue if you need further assistance.
