### ISSUE TITLE
unrecognized option '--addping'

### ISSUE THREAD

**Issue by rsromanovskiy** [gitbls/internet-monitor#6]
/opt/workprograms/platform-tools$ sudo /usr/local/bin/internet-monitor --syslog --interval 1 --addping "10.xx.xx.5 10.xx.xx.6"
internet-monitor: unrecognized option '--addping'
? internet-monitor: Command parse failed

**Comment by gitbls** [comment]
I'm sorry that you have apparently missed the notification on this GitHub that this app is retired, and thus no longer supported.

Please refer to the new improved app at https://github.com/gitbls/imon
